version: 2.1
# can remove postgres from here, the test are not running on it, will let it for now
jobs:
  checkout_code:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/project
          paths:
            - ./*
  build-and-test-spring:
    working_directory: ~/project/spring-app
    parallelism: 4
    docker:
      - image: cimg/openjdk:21.0.2
      - image: cimg/postgres:16.2
        environment:
          POSTGRES_DB: wellness
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
        command: ["postgres", "-c", "port=5444"]
    steps:
      - attach_workspace:
          at: ~/project
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          key: spring-dependencies-{{ checksum "pom.xml" }}
      - run:
          name: List files
          command: ls -l
      - run:
            name: Waiting for POSTGRES to be ready
            command: |
              for i in `seq 1 10`;
              do
                nc -z 127.0.0.1 5444 && echo Success && exit 0
                echo -n .
                sleep 1
              done
              echo Failed waiting for POSTGRES && exit 1
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - save_cache:
          key: spring-dependencies-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2
      - run:
          name: Prepare Test Splitting
          command: |
            mkdir -p /tmp/tests
            circleci tests glob "src/test/java/**/*.java" > /tmp/tests/test_list.txt
      - run:
          name: Run Tests
          command: |
            TEST_CLASSES=$(cat /tmp/tests/test_list.txt | sed 's|src/test/java/||g' | sed 's|/|.|g' | sed 's|.java||g')
            TEST_CLASSES=$(echo $TEST_CLASSES | circleci tests split --split-by=timings --timings-type=classname)
            mvn test -Dtest=$(echo $TEST_CLASSES | tr '\n' ',' | sed 's/,$//')
          no_output_timeout: 30m
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results/junit
      - store_artifacts:
          path: target/*.jar
          destination: build-artifacts
  build-next:
    working_directory: ~/project/client-next
    docker:
      - image: cimg/node:lts
    environment:
      NEXTAUTH_URL: "http://localhost:3000"
      NEXTAUTH_SECRET: "tgY5i4Ea/GZIYMC3J76rANVMf/Cyj0410bSulEicArM="
      NEXT_PUBLIC_SPRING: "http://localhost:8080"
      NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: "lamatutorial"
    steps:
      - attach_workspace:
          at: ~/project
      - restore_cache:
          key: node-dependencies-{{ checksum "package.json" }}
      - run:
          name: List files
          command: ls -l
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: node-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build
          command: npm run build
      - store_artifacts:
          path: .next
          destination: next-build-artifacts
   

workflows:
  build-and-test:
    jobs:
      - checkout_code
      - build-and-test-spring:
          requires:
            - checkout_code
      - build-next:
          requires:
            - checkout_code