services:
  postgres:
    image: postgres:latest
    container_name: wellness_postgres_reactive
    environment:
      POSTGRES_DB: wellness
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wellness-spring

  spring-app:
    container_name: wellness_spring_reactive
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - postgres
    networks:
      - wellness-spring

volumes:
  postgres_data:
networks:
  wellness-spring:
    driver: bridge
